### ISSUE TITLE
Showing blank screen when open

### ISSUE THREAD

**Issue by VinodKumarGaur** [Turtlebody/android-doc-picker#3]
CursorHelper: where: _data LIKE ? OR _data LIKE ? OR _data LIKE ? OR _data LIKE ? OR _data LIKE ? OR _data LIKE ? OR _data LIKE ? OR _data LIKE ? OR _data LIKE ? OR _data LIKE ? OR _data LIKE ? OR _data LIKE ? OR _data LIKE ? OR _data LIKE ?) GROUP BY (parent
/CursorHelper: args: [%.pdf, %.ppt, %.pptx, %.key, %.odp, %.pps, %.xls, %.xlsx, %.ods, %.xlr, %.doc, %.docx, %.txt, %.log]
FA: Connection attempt already in progress
FA: Connection attempt already in progress
/System.err: java.lang.IllegalArgumentException: Invalid column COUNT(_data) AS dataCount
System.err:     at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:170)
/System.err:     at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
System.err:     at android.content.ContentProviderProxy.query(ContentProviderNative.java:423)
/System.err:     at android.content.ContentResolver.query(ContentResolver.java:946)
System.err:     at android.content.ContentResolver.query(ContentResolver.java:881)
/System.err:     at android.content.ContentResolver.query(ContentResolver.java:837)
System.err:     at com.greentoad.turtlebody.docpicker.core.CursorHelper.getDocFolderCursor(CursorHelper.kt:24)
/System.err:     at com.greentoad.turtlebody.docpicker.core.FileManager.fetchAudioFolderList(FileManager.kt:26)
/System.err:     at com.greentoad.turtlebody.docpicker.ui.components.folder.DocFolderFragment$fetchDocFolders$bucketFetch$1.call(DocFolderFragment.kt:112)
/System.err:     at com.greentoad.turtlebody.docpicker.ui.components.folder.DocFolderFragment$fetchDocFolders$bucketFetch$1.call(DocFolderFragment.kt:29)
/System.err:     at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
/System.err:     at io.reactivex.Single.subscribe(Single.java:3603)
/System.err:     at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
/System.err:     at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
/System.err:     at java.lang.Thread.run(Thread.java:919)
I/DocFolderFragment: error: Invalid column COUNT(_data) AS dataCount
FA: Connected to remote service
/FA: Processing queued up service tasks: 4
FA: Inactivity, disconnecting from the service

**Comment by mayankattoinfotech** [comment]
This is happening in Android Q

**Comment by cyberneid** [comment]
Same issue here. 
Any solution?
